# Site
name: "Nipponija"
title: "Nipponija - Nippon and me"
description: "Story about our life in Japan"
logo: '/assets/images/logo.png'
favicon: '/assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-111974679-3'
disqus: 'nipponija'
# mailchimp-list: 'https://xxx.list-manage.com/subscribe/post?u=xxx&amp;id=xxx'
include: ["_pages"]
permalink: /:title/
email: nipponijablog@gmail.com

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-responsive-image
  
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

collections:
  - authors


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-7564009079906606"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

responsive_image:
  template: _includes/responsive-image.html
  base_path: assets
  output_path_format: assets/resized/%{width}/%{basename}
  default_quality: 80
  strip: true
  sizes: 
    - width: 350 # small front page thumb for featured image
      quality: 60
    - width: 640 # mobile version of images
      quality: 70
    - width: 730 # large front page thumb for featured images, regular post image as well
      quality: 75
    - width: 940 # featured image in post
      quality: 75
    - width: 1366 # gallery image size 1
    - width: 1920 # gallery image size 2 

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

defaults:
  -
    scope:
      path: "admin"
    values:
      sitemap: false
